@extends('layouts.dashboard')

@section('title', 'Security Guard Dashboard — Nestora')

@section('content')
<div class="db-header" style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem;">
    <div>
        <h1 class="db-title">Gate Security Guard Terminal</h1>
        <p class="db-subtitle">Verify resident guest codes, register walk-in delivery riders, and report security incidents.</p>
    </div>
    
    <!-- Emergency Panic dispatch button -->
    <a href="{{ route('security.emergency') }}" class="btn btn-danger" style="background-color: var(--color-emergency); font-size: 0.9rem; animation: pulse 2s infinite; border: 1px solid #fda4af;">
        <x-icon name="alarm" alt="" size="1.25rem" class="app-icon-on-danger" />
        Sound Gate Alarm
    </a>
</div>

@if ($emergencies->isNotEmpty())
    <div class="card" style="margin-bottom: 2rem; border: 2px solid #fda4af;">
        <div style="display: flex; justify-content: space-between; align-items: center; gap: 1rem; margin-bottom: 1rem;">
            <h3 style="color: var(--color-emergency);">Active Resident Emergencies</h3>
            <a href="{{ route('security.emergency') }}" class="btn btn-danger btn-sm">Open Emergency Panel</a>
        </div>

        @foreach ($emergencies as $emergency)
            <div style="display: flex; justify-content: space-between; gap: 1rem; padding: 0.75rem 0; border-top: 1px solid var(--border-color);">
                <div>
                    <strong>#AL-{{ $emergency->id }} {{ ucfirst($emergency->type) }}</strong>
                    <div class="text-muted text-xs">
                        {{ $emergency->resident?->name }} - Flat {{ $emergency->flat?->flat_number ?? 'unassigned' }}
                    </div>
                </div>
                <span class="badge badge-emergency">{{ str_replace('_', ' ', $emergency->status) }}</span>
            </div>
        @endforeach
    </div>
@endif

<!-- Giant Pre-Approved Code Search Widget -->
<div class="card" style="margin-bottom: 2rem; background: linear-gradient(135deg, rgba(79, 70, 229, 0.02) 0%, rgba(255, 255, 255, 0) 100%); border: 1px solid rgba(79, 70, 229, 0.15); padding: 2rem;">
    <h3 style="font-size: 1.2rem; color: var(--primary-color); margin-bottom: 0.75rem; text-align: center;">Verify Pre-Approved Visitor Passcode</h3>
    <p style="font-size: 0.85rem; color: var(--text-secondary); text-align: center; max-width: 480px; margin: 0 auto 1.5rem auto;">
        Ask the guest or rider for their 6-digit passcode (e.g. <code>N-5509</code>) generated by the resident.
    </p>
    
    <form action="{{ url('/security/checkin') }}" method="GET" style="max-width: 500px; margin: 0 auto; display: flex; gap: 0.75rem;">
        <input type="text" name="passcode" class="form-control" placeholder="Enter code (e.g. N-5509)" required style="text-align: center; font-size: 1.15rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; height: 3rem;">
        <button type="submit" class="btn btn-primary" style="height: 3rem; font-weight: 700;">Verify Code</button>
    </form>
</div>

<!-- Operational Stat Cards Grid -->
<div class="grid grid-4" style="margin-bottom: 2rem;">
    <!-- Currently Inside -->
    <div class="stat-card">
        <div class="stat-card-left">
            <span class="stat-label-text">Visitors Inside</span>
            <span class="stat-val" style="font-size: 1.6rem;">3 Visitors</span>
            <span style="font-size: 0.75rem; color: var(--text-secondary); margin-top: 0.25rem;">Active check-ins</span>
        </div>
        <div class="stat-icon primary">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width: 1.5rem; height: 1.5rem;">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
            </svg>
        </div>
    </div>

    <!-- Checked Out Today -->
    <div class="stat-card">
        <div class="stat-card-left">
            <span class="stat-label-text">Checked Out Today</span>
            <span class="stat-val" style="font-size: 1.6rem;">8 Visitors</span>
            <span style="font-size: 0.75rem; color: var(--color-approved); font-weight: 600; margin-top: 0.25rem;">Gate traffic cleared</span>
        </div>
        <div class="stat-icon success" style="background-color: var(--bg-approved); color: var(--color-approved);">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width: 1.5rem; height: 1.5rem;">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
        </div>
    </div>

    <!-- Pre-Approved Scheduled -->
    <div class="stat-card">
        <div class="stat-card-left">
            <span class="stat-label-text">Scheduled Today</span>
            <span class="stat-val" style="font-size: 1.6rem;">5 Passes</span>
            <span style="font-size: 0.75rem; color: var(--text-secondary); margin-top: 0.25rem;">Pre-approved guests expected</span>
        </div>
        <div class="stat-icon secondary" style="background-color: var(--secondary-light); color: var(--secondary-color);">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width: 1.5rem; height: 1.5rem;">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
            </svg>
        </div>
    </div>

    <!-- Incidents File -->
    <div class="stat-card">
        <div class="stat-card-left">
            <span class="stat-label-text">Incidents Logged</span>
            <span class="stat-val" style="font-size: 1.6rem;">1 Report</span>
            <span style="font-size: 0.75rem; color: var(--text-secondary); margin-top: 0.25rem;">This week</span>
        </div>
        <div class="stat-icon warning">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width: 1.5rem; height: 1.5rem;">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
        </div>
    </div>
</div>

<!-- Main Area Columns -->
<div class="grid grid-3" style="align-items: start;">
    
    <!-- Column 1 & 2: Recent Gate Logs -->
    <div style="grid-column: span 2; display: flex; flex-direction: column; gap: 2rem;">
        
        <!-- Live checked in visitors -->
        <div class="card">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.25rem;">
                <h3 style="font-size: 1.2rem;">Live Gate Activity log</h3>
                <a href="{{ url('/security/logs') }}" style="font-size: 0.85rem; font-weight: 600;">View All Logs</a>
            </div>
            
            <table class="db-table" style="font-size: 0.875rem;">
                <thead>
                    <tr>
                        <th>Visitor Details</th>
                        <th>Dest. Flat</th>
                        <th>Check-In Time</th>
                        <th>Category</th>
                        <th style="text-align: right;">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style="background-color: rgba(79, 70, 229, 0.01);">
                        <td style="font-weight: 600;">
                            Farhan Alvi
                            <div style="font-size: 0.75rem; color: var(--text-muted);">Pass: N-5509 | Dhaka Metro-Ha-1234</div>
                        </td>
                        <td style="font-weight: 700;">Flat 3B (ullas)</td>
                        <td>Today, 10:12 AM</td>
                        <td><span class="badge badge-unpaid" style="background-color: var(--secondary-light); color: var(--secondary-color);">Delivery</span></td>
                        <td style="text-align: right;">
                            <a href="{{ url('/security/checkout?passcode=N-5509') }}" class="btn btn-outline btn-sm">Check-Out</a>
                        </td>
                    </tr>
                    <tr>
                        <td style="font-weight: 600;">
                            Walk-In Electrician
                            <div style="font-size: 0.75rem; color: var(--text-muted);">NID Verified | Manual Entry</div>
                        </td>
                        <td style="font-weight: 700;">Flat 5A (Karim Alvi)</td>
                        <td>Today, 09:30 AM</td>
                        <td><span class="badge badge-approved" style="background-color: #fee2e2; color: #ef4444;">Service Repair</span></td>
                        <td style="text-align: right;">
                            <a href="{{ url('/security/checkout?manual=1') }}" class="btn btn-outline btn-sm">Check-Out</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>

    <!-- Column 3: Desk actions shortcuts -->
    <div style="display: flex; flex-direction: column; gap: 2rem;">
        
        <!-- Registration shortcuts panel -->
        <div class="card" style="padding: 1.5rem; background-color: var(--primary-light); border-color: rgba(79, 70, 229, 0.15);">
            <h3 style="font-size: 1.15rem; color: var(--primary-color); margin-bottom: 1.25rem;">Desk Registry Tools</h3>
            
            <div style="display: flex; flex-direction: column; gap: 0.75rem;">
                <a href="{{ url('/security/checkin') }}" class="btn btn-primary" style="justify-content: center; font-size: 0.85rem;">
                    Register Walk-In Visitor
                </a>
                <a href="{{ url('/security/checkout') }}" class="btn btn-outline" style="justify-content: center; font-size: 0.85rem; background-color: white;">
                    Check-Out Guest / Rider
                </a>
                <a href="{{ url('/security/incidents') }}" class="btn btn-outline" style="justify-content: center; font-size: 0.85rem; background-color: white;">
                    File Security Incident
                </a>
            </div>
        </div>

        <!-- Phone contact directories -->
        <div class="card" style="padding: 1.5rem;">
            <h3 style="font-size: 1.1rem; margin-bottom: 1rem;">Society Hotline Directory</h3>
            <div style="display: flex; flex-direction: column; gap: 0.75rem; font-size: 0.825rem;">
                <div style="display: flex; justify-content: space-between;">
                    <span class="text-muted">Building Manager Office:</span>
                    <strong style="color: var(--text-primary);">+880 1700 000001</strong>
                </div>
                <div style="display: flex; justify-content: space-between;">
                    <span class="text-muted">Gate 2 Guard Post:</span>
                    <strong style="color: var(--text-primary);">Ext. 102</strong>
                </div>
                <div style="display: flex; justify-content: space-between; border-top: 1px solid var(--border-color); padding-top: 0.5rem; margin-top: 0.25rem;">
                    <span class="text-muted">Standby Electrician:</span>
                    <strong style="color: var(--primary-color);">+880 1812 098766</strong>
                </div>
            </div>
        </div>

    </div>
</div>
@endsection
