@extends('layouts.dashboard')

@section('title', 'Bill Details - Nestora')

@section('content')
<div class="db-header" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem;">
    <div>
        <a href="{{ route('resident.bills.index') }}" style="display: flex; align-items: center; gap: 0.25rem; font-size: 0.85rem; font-weight: 600; color: var(--text-secondary); margin-bottom: 0.5rem;">
            Back to Bills List
        </a>
        <h1 class="db-title" style="font-size: 1.5rem;">Invoice {{ $bill?->bill_number ? '#'.$bill->bill_number : '#B-9872' }}</h1>
    </div>

    <div style="display: flex; gap: 0.75rem;">
        <button type="button" class="btn btn-outline btn-sm" onclick="window.print();">Print Invoice</button>
        @if ($bill && $bill->status !== 'paid' && $paymentTransaction)
            <a href="{{ route('payments.show', $paymentTransaction->payment_token) }}" class="btn btn-primary btn-sm">Pay Bill</a>
        @endif
    </div>
</div>

@if (! $bill)
    <div class="alert alert-danger">This demo bill is not connected to the database. Open a bill from your billing list.</div>
@else
<div class="grid grid-3" style="align-items:start; gap:1.5rem;">
    <div class="card-static" style="grid-column:span 2; background-color: #ffffff; padding: 3rem; border-radius: var(--radius-lg); box-shadow: var(--shadow-sm); border: 1px solid var(--border-color);">
        <div style="display: flex; justify-content: space-between; border-bottom: 2px solid var(--border-color); padding-bottom: 2rem; margin-bottom: 2rem; flex-wrap: wrap; gap: 1rem;">
            <div>
                <h2 class="logo" style="margin-bottom: 0.5rem;">Nestora<span>.</span></h2>
                <p style="font-size: 0.8rem; color: var(--text-muted); margin-bottom: 0;">Smart Apartment Management Made Simple</p>
            </div>
            <div style="text-align: right;">
                <div style="font-weight: 800; font-size: 1.25rem; color: var(--text-primary);">INVOICE</div>
                <div style="font-size: 0.9rem; color: var(--text-secondary); margin-top: 0.25rem;">Invoice No: {{ $bill->bill_number }}</div>
                <div style="margin-top: 0.5rem;"><span class="badge badge-{{ $bill->status === 'paid' ? 'paid' : 'unpaid' }}">{{ str_replace('_', ' ', $bill->status) }}</span></div>
            </div>
        </div>

        <div class="grid grid-2" style="margin-bottom: 2.5rem; gap: 2rem;">
            <div>
                <h4 style="text-transform: uppercase; font-size: 0.75rem; color: var(--text-muted); letter-spacing: 0.05em; margin-bottom: 0.5rem;">Billed To:</h4>
                <div style="font-weight: 700; font-size: 1rem; color: var(--text-primary);">{{ auth()->user()->name }}</div>
                <div style="font-size: 0.875rem; color: var(--text-secondary); margin-top: 0.25rem;">
                    {{ $bill->flat?->building?->name ?? 'Nestora Building' }}<br>
                    Flat {{ $bill->flat?->flat_number ?? '-' }}<br>
                    Dhanmondi, Dhaka, Bangladesh
                </div>
            </div>
            <div style="text-align: right; justify-self: end;">
                <h4 style="text-transform: uppercase; font-size: 0.75rem; color: var(--text-muted); letter-spacing: 0.05em; margin-bottom: 0.5rem;">Invoice Dates:</h4>
                <table style="font-size: 0.875rem; color: var(--text-secondary); margin-left: auto;">
                    <tr><td style="padding: 0.25rem 1rem 0.25rem 0; text-align: right;">Billing Month:</td><td style="font-weight: 600; text-align: left;">{{ $bill->billing_month?->format('F Y') }}</td></tr>
                    <tr><td style="padding: 0.25rem 1rem 0.25rem 0; text-align: right; color: var(--color-rejected);">Due Date:</td><td style="font-weight: 700; text-align: left; color: var(--color-rejected);">{{ $bill->due_date?->format('M d, Y') }}</td></tr>
                    @if ($bill->paid_at)
                        <tr><td style="padding: 0.25rem 1rem 0.25rem 0; text-align: right;">Paid At:</td><td style="font-weight: 600; text-align: left;">{{ $bill->paid_at?->format('M d, Y H:i') }}</td></tr>
                    @endif
                </table>
            </div>
        </div>

        <table class="db-table" style="margin-bottom: 2rem;">
            <thead>
                <tr>
                    <th>Item Description</th>
                    <th style="text-align: right;">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="font-weight: 600;">{{ str_replace('_', ' ', ucfirst($bill->type)) }}<div style="font-weight: normal; font-size: 0.8rem; color: var(--text-muted);">Rent, monthly dues, or apartment service charge generated by management.</div></td>
                    <td style="font-weight: 600; text-align: right;"><span class="money"><x-taka />{{ number_format((float) $bill->amount, 2) }}</span></td>
                </tr>
            </tbody>
        </table>

        <div style="display: flex; justify-content: flex-end;">
            <div style="width: 100%; max-width: 340px;">
                <div style="display: flex; justify-content: space-between; padding: 0.75rem 0; font-size: 1.15rem; border-bottom: 2px double var(--border-color); margin-bottom: 1.5rem;">
                    <span style="font-weight: 700; color: var(--text-primary);">Total Due:</span>
                    <span class="money" style="font-weight: 800; color: var(--primary-color);"><x-taka />{{ number_format((float) $bill->amount, 2) }}</span>
                </div>
            </div>
        </div>
    </div>

    <div class="card" style="text-align:center;">
        <h3 style="margin-bottom:1rem;">Nestora Pay QR</h3>
        @if ($bill->status === 'paid')
            <span class="badge badge-paid" style="margin-bottom:1rem;">Payment Completed</span>
            <p class="text-muted" style="font-size:.85rem;">This bill was paid through Nestora Pay or verified by management.</p>
        @elseif ($paymentTransaction)
            <img src="{{ route('payments.qr', $paymentTransaction->payment_token) }}" alt="Payment QR for {{ $bill->bill_number }}" style="width:260px; max-width:100%; border:1px solid var(--border-color); border-radius:var(--radius-md); padding:.75rem; background:#fff; margin-bottom:1rem;">
            <p style="font-size:.85rem; color:var(--text-secondary); line-height:1.5;">Scan this QR or click below to open the secure Nestora Pay page.</p>
            <a href="{{ route('payments.show', $paymentTransaction->payment_token) }}" class="btn btn-primary" style="width:100%; justify-content:center;">Open Secure Pay</a>
            <div style="margin-top:1rem; font-size:.75rem; color:var(--text-muted);">Session: {{ $paymentTransaction->transaction_number }}</div>
        @endif
    </div>
</div>
@endif
@endsection
